// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh5L6sFsCCYvH-xXrw_CvBEarAAmRZ67g',
    appId: '1:832121767989:android:7a50a98a7e6e32063e497c',
    messagingSenderId: '832121767989',
    projectId: 'giphy-app-test',
    storageBucket: 'giphy-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkeGZi1jeegvD7IJ1kM2JkR3AVCYjDKx8',
    appId: '1:832121767989:ios:feffa972925c0d023e497c',
    messagingSenderId: '832121767989',
    projectId: 'giphy-app-test',
    storageBucket: 'giphy-app-test.appspot.com',
    androidClientId: '832121767989-295kn51kfae78atb51v6ug2anc9g55r3.apps.googleusercontent.com',
    iosClientId: '832121767989-6rt9jhole1le1v76n1qe0riifuf1jgtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.giphyAppTest',
  );

}